[profile.default]
src = "src"
test = 'test'
out = "out"
libs = ["lib"]

# 重新映射
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
